POST http://127.0.0.1:8000/auth
Content-type: application/json

{
    "email": "haln_01@proton.me",
    "password": "test"
}

###

POST http://127.0.0.1:8000/signin
Content-type: application/json

{
    "email": "haln_01@proton.me",
    "password": "test"
}

###

POST http://127.0.0.1:8000/createposts
Content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbG5fMDFAcHJvdG9uLm1lIiwicGFzc3dvcmQiOiJ0ZXN0IiwiaXNzIjoiRWR1QnVkZHkiLCJzdWIiOiJoYWxuXzAxQHByb3Rvbi5tZSIsImV4cCI6MTY4ODkzNDQ1OCwibmJmIjoxNjg4ODQ4MDU4LCJpYXQiOjE2ODg4NDgwNTh9._k3n8xlXKHnE8dT9OPHTlLbOgc9dBAN28BraLFQjLS4

{
    "course": "MATH101",
    "role": "student"
}

###

GET http://127.0.0.1:8000/test
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbG5fMDFAcHJvdG9uLm1lIiwicGFzc3dvcmQiOiJ0ZXN0IiwiaXNzIjoiRWR1QnVkZHkiLCJzdWIiOiJoYWxuXzAxQHByb3Rvbi5tZSIsImV4cCI6MTY4ODkyOTkwMCwibmJmIjoxNjg4ODQzNTAwLCJpYXQiOjE2ODg4NDM1MDB9.heS2BJP1i6TVjOBHzp2_li4ymlc6BUHhNBPlyGJeq_Y

###

POST http://127.0.0.1:8000/list
Content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbG5fMDFAcHJvdG9uLm1lIiwicGFzc3dvcmQiOiJ0ZXN0IiwiaXNzIjoiRWR1QnVkZHkiLCJzdWIiOiJoYWxuXzAxQHByb3Rvbi5tZSIsImV4cCI6MTY4ODkyOTkwMCwibmJmIjoxNjg4ODQzNTAwLCJpYXQiOjE2ODg4NDM1MDB9.heS2BJP1i6TVjOBHzp2_li4ymlc6BUHhNBPlyGJeq_Y

{
    "role": "student",
    "courses": ["math101", "csc230"]
}

###
POST https://eng-comp.onrender.com/auth

{
    "role": "student",
    "courses": ["math101", "csc230"]
}
