POST http://127.0.0.1:8000/auth
Content-type: application/json

{
    "email": "haln_01@proton.me",
    "password": "test"
}


POST http://127.0.0.1:8000/createposts
Content-type: application/json

{
    "email": "haln_01@proton.me",
    "course": "Math101",
    "role": "student"
}

